name: Zig Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Specify a tag name for manual release (e.g., v1.0.0). Required for manual releases."
        required: false
        type: string
  push:
    tags: ["v*"]

permissions:
  contents: write # This is the key permission for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1

      - name: Create .env file
        run: |
          mkdir -p src/lib
          echo "maptiler_api_key = ${{ secrets.MAPTILER_API_KEY }}" > src/lib/.env
        shell: bash

      - name: Build Zig application
        run: zig build install --release=fast

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: zig-out/bin/app

  release:
    runs-on: ubuntu-latest
    needs: build
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != '')
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: binary-macos-latest
          path: dist/macos

      - name: Prepare release files
        run: |
          zip -r dist/weather-app-local-macos.zip dist/macos
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || github.ref }}
          name: Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || github.ref }}
          body: |
            Automated release from GitHub Actions.
            Binaries for macOS.
          files: |
            dist/weather-app-local-macos.zip
